# creation of matrix

In [1]:
import numpy as np # for array
import matplotlib.pyplot as plt

In [2]:
M=np.array([[3,4],[2,8],[1,9]])
M 

array([[3, 4],
       [2, 8],
       [1, 9]])

In [3]:
M.shape

(3, 2)

In [4]:
M.min()

1

In [5]:
M.size

6

In [6]:
type(M)

numpy.ndarray

In [7]:
v = np.array([4,6,5,3,1,7,6,3])

In [8]:
v.size

8

In [9]:
v.reshape(4,2)

array([[4, 6],
       [5, 3],
       [1, 7],
       [6, 3]])

In [10]:
v.reshape(2,4)

array([[4, 6, 5, 3],
       [1, 7, 6, 3]])

In [11]:
v.reshape(1,8)

array([[4, 6, 5, 3, 1, 7, 6, 3]])

In [12]:
v.reshape(8,1)

array([[4],
       [6],
       [5],
       [3],
       [1],
       [7],
       [6],
       [3]])

In [13]:
v.reshape(3,3)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [14]:
M.dtype

dtype('int32')

In [15]:
M=np.array([[3,4],[2,8],[1,9]] , dtype=np.int8)
M

array([[3, 4],
       [2, 8],
       [1, 9]], dtype=int8)

In [16]:
M=np.array([[3,4,8,0],[2,8,1,3],[1,9,5,6]] , dtype=np.int8)
M

array([[3, 4, 8, 0],
       [2, 8, 1, 3],
       [1, 9, 5, 6]], dtype=int8)

In [17]:
M.flatten() # return a copy of an array into one dimention

array([3, 4, 8, 0, 2, 8, 1, 3, 1, 9, 5, 6], dtype=int8)

In [18]:
M.reshape(-1,3)

array([[3, 4, 8],
       [0, 2, 8],
       [1, 3, 1],
       [9, 5, 6]], dtype=int8)

In [19]:
M.reshape(3,-1)

array([[3, 4, 8, 0],
       [2, 8, 1, 3],
       [1, 9, 5, 6]], dtype=int8)

In [20]:
M.reshape(-1,2)

array([[3, 4],
       [8, 0],
       [2, 8],
       [1, 3],
       [1, 9],
       [5, 6]], dtype=int8)

In [21]:
M.reshape(-1)

array([3, 4, 8, 0, 2, 8, 1, 3, 1, 9, 5, 6], dtype=int8)

In [22]:
# help(M.sort)

In [23]:
M

array([[3, 4, 8, 0],
       [2, 8, 1, 3],
       [1, 9, 5, 6]], dtype=int8)

In [24]:
M[1][2]

1

In [25]:
for row in M:
    print(row)

[3 4 8 0]
[2 8 1 3]
[1 9 5 6]


In [26]:
for row in M:
    for value in row:
        print(value,end=' ')
    print()

3 4 8 0 
2 8 1 3 
1 9 5 6 


In [27]:
for row in M:
    print(*row)

3 4 8 0
2 8 1 3
1 9 5 6


# Addition

In [28]:
M1=np.array([[4,5,6],[2,1,9],[0,2,8]])
M2=np.array([[2,5,7],[0,8,7],[6,4,3]])

In [29]:
M3=M1+M2

In [30]:
M3

array([[ 6, 10, 13],
       [ 2,  9, 16],
       [ 6,  6, 11]])

In [31]:
M3=M1-M2
M3

array([[ 2,  0, -1],
       [ 2, -7,  2],
       [-6, -2,  5]])

In [32]:
M3=M1*M2
M3

array([[ 8, 25, 42],
       [ 0,  8, 63],
       [ 0,  8, 24]])

# scalar multiplication

In [33]:
M1,M2*2

(array([[4, 5, 6],
        [2, 1, 9],
        [0, 2, 8]]),
 array([[ 4, 10, 14],
        [ 0, 16, 14],
        [12,  8,  6]]))

In [34]:
M1+10

array([[14, 15, 16],
       [12, 11, 19],
       [10, 12, 18]])

In [35]:
M3=2 * (M1+M2)

In [36]:
M4=2 * M1+ 2 * M2

In [37]:
M3,M4

(array([[12, 20, 26],
        [ 4, 18, 32],
        [12, 12, 22]]),
 array([[12, 20, 26],
        [ 4, 18, 32],
        [12, 12, 22]]))

In [38]:
M1 * (2+1)   #[[4,5,6],[2,1,9],[0,2,8]]

array([[12, 15, 18],
       [ 6,  3, 27],
       [ 0,  6, 24]])

In [39]:
M1 * 2 + M1 *1

array([[12, 15, 18],
       [ 6,  3, 27],
       [ 0,  6, 24]])

In [40]:
1 * M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [41]:
-1 * M1

array([[-4, -5, -6],
       [-2, -1, -9],
       [ 0, -2, -8]])

# Multiplcation of matrix

In [42]:
M1 , M2

(array([[4, 5, 6],
        [2, 1, 9],
        [0, 2, 8]]),
 array([[2, 5, 7],
        [0, 8, 7],
        [6, 4, 3]]))

In [43]:
 M1 * M2

array([[ 8, 25, 42],
       [ 0,  8, 63],
       [ 0,  8, 24]])

In [44]:
M1 @ M2

array([[44, 84, 81],
       [58, 54, 48],
       [48, 48, 38]])

In [45]:
M2 @ M1

array([[ 18,  29, 113],
       [ 16,  22, 128],
       [ 32,  40,  96]])

In [46]:
M3

array([[12, 20, 26],
       [ 4, 18, 32],
       [12, 12, 22]])

In [47]:
M1 @ (M2 @ M3) , (M1 @ M2) @ M3

(array([[1836, 3364, 5614],
        [1488, 2708, 4292],
        [1224, 2280, 3620]]),
 array([[1836, 3364, 5614],
        [1488, 2708, 4292],
        [1224, 2280, 3620]]))

In [48]:
M1 @ (M2 + M3) 

array([[184, 326, 477],
       [194, 220, 330],
       [152, 180, 278]])

In [49]:
(M1 @ M2) + (M1 @ M3)

array([[184, 326, 477],
       [194, 220, 330],
       [152, 180, 278]])

In [50]:
(M1 + M2) @ M3 

array([[268, 456, 762],
       [252, 394, 692],
       [228, 360, 590]])

In [51]:
(M1 @ M3) +( M2 @ M3)

array([[268, 456, 762],
       [252, 394, 692],
       [228, 360, 590]])

In [52]:
np.matmul(M1 , M2)

array([[44, 84, 81],
       [58, 54, 48],
       [48, 48, 38]])

# transpose

In [53]:
M1.T

array([[4, 2, 0],
       [5, 1, 2],
       [6, 9, 8]])

In [54]:
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [55]:
np.transpose(M1)

array([[4, 2, 0],
       [5, 1, 2],
       [6, 9, 8]])

In [56]:
import numpy as np
rows = int(input("Enter the rows"))
cols = int(input("Enter the col"))
mat = np.zeros(rows * cols, dtype=np.int16)
print(mat)
for i in range(len(mat)):
        mat[i]=int(input("Enter the value"))

mat = mat.reshape(rows,cols)
print('matrix:\n',mat)
print('Transpose:\n',mat.T)

Enter the rows 2
Enter the col 6


[0 0 0 0 0 0 0 0 0 0 0 0]


Enter the value 8
Enter the value 6
Enter the value 7
Enter the value 8
Enter the value 9
Enter the value 4
Enter the value 4
Enter the value 8
Enter the value 9
Enter the value 7
Enter the value 0
Enter the value 3


matrix:
 [[8 6 7 8 9 4]
 [4 8 9 7 0 3]]
Transpose:
 [[8 4]
 [6 8]
 [7 9]
 [8 7]
 [9 0]
 [4 3]]


In [57]:
M=np.array([[3,4],[2,8],[1,9]])
M

array([[3, 4],
       [2, 8],
       [1, 9]])

In [58]:
M.T.T

array([[3, 4],
       [2, 8],
       [1, 9]])

In [59]:
M1=np.array([[4,5,6],[2,1,9],[0,2,8]])
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [60]:
(M @ M1).T,   M1.T @ M.T

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [63]:
M1=np.array([[4,5,6],[2,1,9],[0,2,8]])
M2=np.array([[2,5,7],[0,8,7],[6,4,3]])
M1
M2

array([[2, 5, 7],
       [0, 8, 7],
       [6, 4, 3]])

In [62]:
(M1 @ M2).T,   M2.T @ M1.T

(array([[44, 58, 48],
        [84, 54, 48],
        [81, 48, 38]]),
 array([[44, 58, 48],
        [84, 54, 48],
        [81, 48, 38]]))

# TRACE OF THR MATRIX

In [64]:
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [67]:
add=0
rn=0
for row in M1:
    add = add + row[rn]
    rn+=1

In [68]:
add

13

In [69]:
np.trace(M1)

13

In [70]:
M3=np.array([[3,4,8,0],[2,8,1,3],[1,9,5,6]]) 
M3

array([[3, 4, 8, 0],
       [2, 8, 1, 3],
       [1, 9, 5, 6]])

In [71]:
np.trace(M3)

16

In [72]:
np.trace(M1 @ M2) , np.trace(M2 @ M1) 

(136, 136)

In [73]:
np.trace(M1 ) , np.trace( M1 .T) 

(13, 13)

In [74]:
2 * np.trace(M1)  , np.trace(2 * M1)

(26, 26)

In [75]:
np.trace (M1 + M2)   ,  np.trace(M1) + np.trace(M2)

(26, 26)

# Determinant of matrix

In [76]:
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [77]:
np.linalg.det(M1)  #linalg = linear algebra

-95.99999999999999

In [78]:
np.linalg.det(M2)

-133.99999999999997

## Inverse of the matrix

In [79]:
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [80]:
np.linalg.inv(M1)

array([[ 0.10416667,  0.29166667, -0.40625   ],
       [ 0.16666667, -0.33333333,  0.25      ],
       [-0.04166667,  0.08333333,  0.0625    ]])

In [81]:
M4 = np.array([[1,2],[2,4]])
M4

array([[1, 2],
       [2, 4]])

In [83]:
np.linalg.matrix_rank(M4)

1

In [85]:
M5 = np.array([[1,2],[3,4]])
np.linalg.matrix_rank(M5)

2

In [86]:
M5

array([[1, 2],
       [3, 4]])

In [88]:
M4 = np.array([[1,2,3],[2,4,6],[1.5,3.0,4.5]])
np.linalg.matrix_rank(M4)

1

In [89]:
M4

array([[1. , 2. , 3. ],
       [2. , 4. , 6. ],
       [1.5, 3. , 4.5]])

In [90]:
M4 = np.array([[1,2,3],[2,4,6],[7,8,9]])
np.linalg.matrix_rank(M4)

2

In [91]:
M4[0]

array([1, 2, 3])

In [92]:
M4[0]*2

array([2, 4, 6])

In [93]:
M4[0] * 1.5

array([1.5, 3. , 4.5])

## row matrix

In [94]:
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [95]:
R = M1.reshape(1,-1)

In [96]:
R

array([[4, 5, 6, 2, 1, 9, 0, 2, 8]])

## Column matrix

In [97]:
C =M1.reshape(-1,1)
C

array([[4],
       [5],
       [6],
       [2],
       [1],
       [9],
       [0],
       [2],
       [8]])

In [98]:
C.shape

(9, 1)

In [99]:
C.T

array([[4, 5, 6, 2, 1, 9, 0, 2, 8]])

In [100]:
R.T

array([[4],
       [5],
       [6],
       [2],
       [1],
       [9],
       [0],
       [2],
       [8]])

## square matrix

In [102]:
def isSqureMatrix(M):
    if M.shape[0]== M.shape[1]:
        return True
    else:
        return False

In [103]:
M1.shape

(3, 3)

In [104]:
isSqureMatrix(M)

False

In [105]:
isSqureMatrix(M1)

True

In [107]:
S = np.zeros([4,4], dtype=np.int8)
S =S + 4

In [108]:
S

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]], dtype=int8)

## Rectangular Matrix

In [109]:
def isRectangleMatrix(M):
    if M.shape[0] != M.shape[1]:
        return True
    else:
        return False
        

In [114]:
M

array([[3, 4],
       [2, 8],
       [1, 9]])

In [113]:
M.shape[1]

2

In [112]:
M.shape[0] 

3

In [110]:
isRectangleMatrix(M1)

False

In [111]:
isRectangleMatrix(M)

True

## Diagonal Matrix

In [115]:
D = np.zeros([4,4], dtype=np.int8)
for i in range(4):
    D[i][i] = 4

D

array([[4, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 4]], dtype=int8)

In [116]:
def isDiagonalMatrix(M):
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            if i != j and M[i][j] !=0:
                return False
    return True

In [118]:
isDiagonalMatrix(D)

True

## Identity Matrix

In [120]:
I = np.zeros([4,4] ,dtype=np.int8)
for i in range(4):
    I[i][i] = 1

I

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [121]:
np.diag(I)

array([1, 1, 1, 1], dtype=int8)

## Symmetric matrix

In [122]:
S1 = np.array([[2,3,6],[3,4,5],[6,5,9]])
S1

array([[2, 3, 6],
       [3, 4, 5],
       [6, 5, 9]])

In [123]:
(S1 == S1.T).sum()

9

In [124]:
S1.size

9

In [126]:
def isSymmetricMatrix(M):
    if (M== M.T).sum() == M.size:
        return True
    else:
        return False

In [128]:
isSymmetricMatrix(S1)

True

In [129]:
isSymmetricMatrix(M1)

False

## Skew symmetric matrix

In [130]:
S2 = np.array([[0,3],[-3,0]])
S2

array([[ 0,  3],
       [-3,  0]])

In [131]:
-S2

array([[ 0, -3],
       [ 3,  0]])

In [132]:
S2.T

array([[ 0, -3],
       [ 3,  0]])

## EigenVectors and EigenValues

In [133]:
# Define a matrix
A = np.array([[-6,3],[4,5]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the eigenvalues
print("Eigenvalues:\n", eigenvalues)

# print the eigenvectors (one per column)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues:
 [-7.  6.]
Eigenvectors:
 [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


In [134]:
A @ eigenvectors

array([[ 6.64078309, -1.45521375],
       [-2.21359436, -5.820855  ]])

In [135]:
eigenvalues * eigenvectors[0]

array([ 6.64078309, -1.45521375])